spring:
  application:
    name: rental-service
    url: ${APP_URL}
  profiles:
    active: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: mail.smtp2go.com
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME} # must be full account email, not just domain
    password: ${MAIL_PASSWORD}
    from: ${MAIL_FROM}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true # optional, helps log SMTP conversation

jwt:
  secret: ${JWT_SECRET}
  expiration: 900000
  refresh-expiration: 6048000

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

razorpay:
  key_id: ${RAZORPAY_KEY_ID}
  key_secret: ${RAZORPAY_KEY_SECRET}

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}
